### PR TITLE
Update README.md on the status of this package.

### LINKED ISSUE #86: dcrticketbuyer has been replaced by the builtin ticketbuyer in dcrwallet. repo should say so

### PR DESCRIPTION
**Pull request by jcvernaleo**
Closes #86

### CODE REVIEW

**Review by jolan — APPROVED** [review]
OK

**Comment by davecgh** [comment]
I would also suggest the code and release bins be removed once the new release is out   It will still be available in history if it's ever needed.

**Comment by jcvernaleo** [comment]
@davecgh after this release I can delete the code in this repo and just leave the obsolete notice.  I'll also close or migrate the issues.  I can't delete the old binaries though since that would break dcrinstall and I want to leave open the ability to use it to install v0.7.0 or other releases for example.

**Comment by raedah** [comment]
If needed, I can migrate over the issues since most of them I opened.

**Comment by jcvernaleo** [comment]
@raedah that would be awesome if you migrate over any issues of yours that are still valid.

**Pull request merged**
