### PR TITLE
update description and example for highpricepenalty

### PR DESCRIPTION
**Pull request by raedah**
Changed description from 'mean' to 'ideal'  since it can be mean, median, or pricetarget.
Added to example conf.

### CODE REVIEW

**Comment by raedah** [comment]
https://github.com/decred/dcrticketbuyer/blob/master/config.go#L61

**Comment by cjepson** [comment]
Please revert the maximum number of tickets per block, then OK to go in

**Comment by raedah** [comment]
@cjepson the max tickets per block was changed to match the true default, see link above. Else, it looks like the default is 5 when its actually 3.

**Comment by cjepson** [comment]
OK, good for merge.

**Pull request merged**
